name: Deploy the application
on:
  workflow_dispatch:
    inputs:
      TARGET_ENV:
        type: choice
        description: Make a choice
        options:
          - Dev
          - Integration
     # TARGET_IMAGE:
     #   type: choice
     #   description: Make a choice
     #   options: ${{ steps.get_files.outputs.environment }}
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
        default: ${{ steps.get_files.outputs.environment }}
          
jobs:
  BROCHURE_API_DEPLOY_PREPARE:
    runs-on: [ 'ubuntu-latest' ]
    steps:
      - name: Printing Input Choice of Environment
        run: |
          echo "Deployment starts with env details as '${{ github.event.inputs.TARGET_ENV }}'"
      - id: get_files
        run: |
          if [ "$GITHUB_REF" = "refs/heads/test" ] then echo "::set-output name=environment::test" elif [ "$GITHUB_REF" = "refs/heads/qa" ] then echo "::set-output name=environment::qa" elif [ "$GITHUB_REF" = "refs/heads/master" ] then echo "::set-output name=environment::production" fi

