name: Deploy the application on EKS

on:
  workflow_dispatch:

jobs:
    deploy:
        environment: dev
        runs-on: ubuntu-latest
        needs: build
        steps:  
            - name: print values
              run: echo  $HTTP_PROXY  | sed 's/./& /g'
