name: Deploy the application on EKS

on:
  workflow_dispatch:
    input:
        TARGET_ENV:
         type: choice
         description: Make a choice
         options:
            - Dev
            - Integration

jobs:
    deploy:
        environment: dev
        runs-on: ubuntu-latest
        needs: build
        steps:  
            - name: print values
              run: echo  "'${{ github.event.inputs.TARGET_ENV }}'"
